export const GET_ALL_VIDEOGAMES= "GET_ALL_VIDEOGAMES";
export const FIND_VIDEOGAMES= "FIND_VIDEOGAMES";
export const VIDEOGAME_DETAIL= "VIDEOGAME_DETAIL";
export const GET_GENRES= "GET_GENRES";
export const FILTER_BY_GENRE= "FILTER_BY_GENRE";
export const FILTER_BY_ORIGIN="FILTER_BY_ORIGIN";
export const ORDER_BY_NAME="ORDER_BY_NAME";
export const ORDER_BY_RATING= "ORDER_BY_RATING";